#pragma once

static const int& CONSTANTS_STANDARD_TILE_SIZE = 16;
static const int& CONSTANTS_STANDARD_TILE_SCALE = 4;

static const int& CONSTANTS_GROUP_MAX_SIZE = 32;

static const int& CONSTANTS_STANDARD_ANIMATION_SPEED = 200;

static const int& CONSTANTS_STANDARD_MOVE_SPEED = 3;

static const int& CONSTANTS_STANDARD_MAP_SCALE = 4;

static const int& CONSTANTS_PLAYER_SPAWN_Y = CONSTANTS_STANDARD_TILE_SIZE * 4;
static const int& CONSTANTS_PLAYER_SPAWN_X = CONSTANTS_STANDARD_TILE_SIZE * 4;
